package com.laioffer.delivery.utils;

public class GeoUtils {
    // NOTE: this file is just an example generated by ChatGPT 4o
    // Feel free to modify or add more to fit your own dev needs

    private static final double EARTH_RADIUS = 6371.0; // 地球半径，单位：千米

    private GeoUtils() {
        // 私有化构造器，防止实例化
    }

    // 根据经纬度计算两点之间的距离（单位：千米）
    public static double calculateDistance(double lat1, double lon1, double lat2, double lon2) {
        double latDistance = Math.toRadians(lat2 - lat1);
        double lonDistance = Math.toRadians(lon2 - lon1);

        double a = Math.sin(latDistance / 2) * Math.sin(latDistance / 2)
                + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2))
                * Math.sin(lonDistance / 2) * Math.sin(lonDistance / 2);

        double c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
        return EARTH_RADIUS * c;
    }
}
